services:
  stepbible:
    build:
      context: .
      dockerfile: Dockerfile
    image: stepbible
    container_name: stepbible
    networks:
      - stepbible_bridge
    volumes:
      - ./data:/home/step/.sword
    environment:
      - DISPLAY=${DISPLAY}
      - JAVA_OPTS=-Dapp.desktop=true -Dstep.desktop=true -Dstep.jetty=true -Djava.net.preferIPv4Stack=true
    tty: true
    stdin_open: true
    restart: unless-stopped
    ports:
      - "8989:8989"


networks:
  stepbible_bridge:
    driver: bridge