services:
  stepbible:
    build:
      context: .
      dockerfile: Dockerfile
    image: stepbible
    container_name: stepbible
    network_mode: host
    volumes:
      - ./data:/home/step/.sword
      - ./web.xml.network:/opt/stepbible/webapps/ROOT/WEB-INF/web.xml
      - ./step.web.properties.network:/opt/stepbible/step.web.properties
    environment:
      - DISPLAY=${DISPLAY}
    tty: true
    stdin_open: true
    restart: unless-stopped