services:
  stepbible:
    build:
      context: .
      dockerfile: Dockerfile
    image: step_bible_docker
    container_name: stepbible
    ports:
      - "8989:8989"
    volumes:
      - ./data:/home/step/.sword
    tty: true
    stdin_open: true
    restart: unless-stopped